name: Build APK

on:
  push:
    branches:
      - main  # غير الفرع إذا لازم

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          python3-pip \
          unzip \
          git \
          build-essential \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          libncurses-dev \
          liblzma-dev \
          libbz2-dev \
          libreadline-dev \
          zlib1g-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: my_app_apk
        path: bin/*.apk
